export const MY_QUESTIONS = [
  {
    id: 1,
    question: "A US$500,000 contract is to be negotiated. Who shall conduct the price negotiation?",
    options: [
      "Financial Controller",
      "Department Manager of PR requestor",
      "Procurement Manager",
      "All of the options"
    ],
    correctAnswer: [3],
    category: "Price Negotiation",
  },
  {
    id: 2,
    question: "Supplier A offers Buyer Z a 5% reduction in price because the RFQ quantity was increased by 10%. The previous purchase was made by Buyer Y 2 weeks ago. Buyer Z proceeds to issue PO to Supplier A using the Repeat Purchase Rule. Can the Repeat Purchase Rule be used in this case?",
    options: [
      "Yes, but the Buyer should negotiate for a price reduction to 10% because the increase in quantity is 10%.",
      "Yes, as long as there are savings, Buyers can use the Repeat Purchase Rule if the last PO issued to the same supplier is within the last 3 months.",
      "No, the Repeat Purchase Rule is not applicable because the last PO must be generated by the same Buyer within the last 3 months.",
      "None of the options"
    ],
    correctAnswer: [3],
    category: "Bid Tab & PO Award",
  },
  {
    id: 3,
    question: "Finance Department has a requirement to buy a new paper shredding machine to replace the current faulty machine. Due to uniformity, BU's policy states to use the same brand and model of paper shredding machine that costs US$600. Which of the following statement is correct?",
    options: [
      "Since the brand and model are determined, Finance Department proceeds to request directly from an authorize distributor to deliver the shredding machine.",
      "Finance Department purchases the shredding machine without a Purchase Order since the cost of US$600 is considered as Minor Purchase.",
      "Finance Department raises a Purchase Requisition and insists Procurement to buy the shredding machine from Supplier A whom is an authorized distributor since it is a BU policy to use the same brand and model of shredding machine.",
      "None of the options"
    ],
    correctAnswer: [3],
    category: "General",
  },
  {
    id: 4,
    question: "Supplier A is listed as the sole supplier for Bearing X in the sole source list. Production Department's user raises a 3-Bid Exemption form and obtained approval from the Department Head and submits it together with the Purchase Requisition to Procurement for the purchase. Buyer then generates a Purchase Order to Supplier A. Is this process correct?",
    options: ["Correct", "Incorrect"],
    correctAnswer: [1],
    category: "General",
  },
  {
    id: 5,
    question: "All SAP enhancement's Change Requests relating to the Purchase-To-Pay module (Material Management) must be approved by Procurement Excellence team.",
    options: ["TRUE", "FALSE"],
    correctAnswer: [0],
    category: "General",
  },
  {
    id: 6,
    question: "There is a global initiative to replace office furniture for all BUs. The estimated total cost is US$600,000. Which of the following statement is correct?",
    options: [
      "Buyer chooses non sealed bid process since office furniture is considered as non-critical items.",
      "Buyer issues tender documents to 3 suppliers and for price protection purposes requests submission of quotations to Buyer's email address only.",
      "Buyer requests to create an e-platform for sealed bid process.",
      "Buyer requests Finance to purchase through non-PO process since office furniture is non-critical."
    ],
    correctAnswer: [2],
    category: "RFQ/RFP",
  },
  {
    id: 7,
    question: "During vendor registration, the vendor refuses to sign the Supplier COPE because the supplier is not agreeable to Clause 6. What should the Buyer do?",
    options: [
      "Buyer should negotiate with vendor to sign the Supplier COPE and seek waiver for Clause 6 only from Procurement Head and BU Head.",
      "Buyer to obtain approval from Procurement Head, BU Head and GMM Head to waive the Supplier COPE.",
      "Buyer should negotiate with vendor to sign the Supplier COPE and seek waiver for Clause 6 only from Procurement Head, BU Head and GMM Head.",
      "Buyer should negotiate with vendor to sign the Supplier COPE and seek waiver for Clause 6 only from BG Head."
    ],
    correctAnswer: [2],
    category: "Supplier Registration & Selection",
  },
  {
    id: 8,
    question: "Which statement is incorrect?",
    options: [
      "3-Bid exemption can only be raised and approved by Procurement.",
      "For a purchase amount that is greater than US$500,000 from a Sole Source, following the RFQ process instead of the sealed bid process is sufficient.",
      "\"Compliance with Sustainability Framework\" is part of Supplier COPE.",
      "PASL suppliers are able to receive up to S$10,000 worth of Purchase Orders within 12 calendar months."
    ],
    correctAnswer: [3],
    category: "General",
  },
  {
    id: 9,
    question: "When a Buyer receives an approved User Specified Source Form, there is no scenario that will need to raise a 3-Bid Exemption Form.",
    options: ["TRUE", "FALSE"],
    correctAnswer: [1],
    category: "PR Creation",
  },
  {
    id: 10,
    question: "Which statement is correct?",
    options: [
      "For a purchase amount that is greater than US$500,000 from a Sole Source, following the RFQ process instead of the sealed bid process is sufficient.",
      "End-users who want to know the Purchase Order price, approval from their Department Manager alone is sufficient.",
      "For government departments, Supplier COPE is not needed.",
      "Technical Evaluation can be completed after Commercial Evaluation."
    ],
    correctAnswer: [0],
    category: "RFQ/RFP",
  },
  {
    id: 11,
    question: "Which two statements are correct?\n(a) Supplier must contact Procurement only to request for a change in bank account details.\n(b) PASL suppliers can be moved to ASL automatically if the total purchase amount exceeds US$10,000 in a calender year.\n(c) A pump that costs US$350 that is used in a production machine can be purchased without a Purchase Order since it is less than US$500.\n(d) DSL is a global supplier status.",
    options: ["(b) and (c)", "(a) and (c)", "(a) and (d)", "(b) and (d)"],
    correctAnswer: [2],
    category: "General",
  },
  {
    id: 12,
    question: "Supplier A has ASL status in 3 BUs (X, Y and Z). If Supplier A commits a COPE violation in BU Z, what is the correct action to take?",
    options: [
      "Downgrade Supplier A to NSL in BU Z only.",
      "Downgrade Supplier A to DSL globally.",
      "Downgrade Supplier A to DSL in BU Z only.",
      "Downgrade Supplier A to NSL in BU X and Y and DSL in BU Z."
    ],
    correctAnswer: [1],
    category: "Supplier Management",
  },
  {
    id: 13,
    question: "Who needs to approve an Urgent PR?",
    options: [
      "End-user's manager and Procurement Manager.",
      "Procurement Manager and BU Head.",
      "End-user's manager and BU Head.",
      "BU Head only."
    ],
    correctAnswer: [2],
    category: "PR Creation",
  },
  {
    id: 14,
    question: "Who should the supplier approach to initiate a change in the supplier's bank account number?",
    options: [
      "Finance department.",
      "Procurement department.",
      "End-user's department.",
      "End-User's department and Finance department"
    ],
    correctAnswer: [1],
    category: "Supplier Registration & Selection",
  },
  {
    id: 15,
    question: "Who is the final approver for non-conformance in Sealed Bids submission?",
    options: ["Procurement Manager", "Procurement Head", "BU Head", "Finance Had"],
    correctAnswer: [1],
    category: "RFQ/RFP",
  },
  {
    id: 16,
    question: "For Projects Procurement, generally supplier's contract format should not be used.",
    options: ["TRUE", "FALSE"],
    correctAnswer: [0],
    category: "Bid Tab & PO Award",
  },
  {
    id: 17,
    question: "If Global Coding System (GCS) shows that a Material Code (MC#1) is in use in another BU A, which is the correct step to take if BU B needs to use this code?",
    options: [
      "Create a local code in SAP of BU B.",
      "Request GCS team to create a new Material Code.",
      "Request for a subscription of MC#1 from GCS to BU B.",
      "None of the options"
    ],
    correctAnswer: [2],
    category: "Global Coding System",
  },
  {
    id: 18,
    question: "Re-qualification of DSL suppliers back to ASL only requires approval from the initiating BU and do not need those BUs that are subscribed to that supplier.",
    options: ["TRUE", "FALSE"],
    correctAnswer: [1],
    category: "Supplier Registration & Selection",
  },
  {
    id: 19,
    question: "For high value purchases that require advanced payments, the Bank Guarantee's value should be:",
    options: ["0.05", "0.1", "0.15", "Same amount as the Advanced Payment"],
    correctAnswer: [3],
    category: "General",
  },
  {
    id: 20,
    question: "Which statement is true about Sole Supplier?",
    options: [
      "Sole Supplier List is valid up to 6 months.",
      "Sole Supplier status is only applicable for specific material codes registered during the point of approval and not for all the material codes supplied by the Sole Supplier.",
      "Approved sole source is an acceptible 3-bid waiver justification.",
      "All of the options"
    ],
    correctAnswer: [3],
    category: "Supplier Registration & Selection",
  },
  {
    id: 21,
    question: "To undelete a deleted Purchase Requisitions in SAP, approval from the End-User's Department Manager is needed.",
    options: ["TRUE", "FALSE"],
    correctAnswer: [1],
    category: "PR Creation",
  },
  {
    id: 22,
    question: "The following list must be maintained by BU Procurement Department:",
    options: [
      "Sole Source list.",
      "Supplier COPE waiver list.",
      "Contract list.",
      "All of the options"
    ],
    correctAnswer: [3],
    category: "General",
  },
  {
    id: 23,
    question: "Which is the correct definition of Inactive Supplier?",
    options: [
      "Suppliers who did not receive RGE's Purchase Order over a consecutive 36 months period from the date of last Purchase Order.",
      "Suppliers who did not receive RGE's RFQ over a consecutive 36 months period from the date of last Purchase Order.",
      "Suppliers who did not receive RGE's Contract over a consecutive 36 months period from the date of last Purchase Order.",
      "None of the options"
    ],
    correctAnswer: [0],
    category: "Supplier Management",
  },
  {
    id: 24,
    question: "Supplier Performance Assessment should be performed for which group of suppliers?\n\n(a) Major Projects suppliers.\n(b) Active critical and strategic mill Suppliers.\n(c) All ASL suppliers.",
    options: ["(a) only.", "(b) only.", "(c) only.", "(a) and (b)."],
    correctAnswer: [3],
    category: "Supplier Management",
  },
  {
    id: 25,
    question: "Which is the correct process to upgrade an Inactive Active supplier in the NSL list back to ASL?",
    options: [
      "Perform full pre-qualification.",
      "Complete Vendor Registration Form (MMF03) and COPE (only if there is a new revision).",
      "Complete Vendor Registration Form (MMF03) and COPE regardless of whether there is a new revision.",
      "None of the options"
    ],
    correctAnswer: [1],
    category: "Supplier Management",
  },
  {
    id: 26,
    question: "Pre-qualification and Supplier COPE signing are not applicable to PASL suppliers.",
    options: ["TRUE", "FALSE"],
    correctAnswer: [1],
    category: "Supplier Registration & Selection",
  },
  {
    id: 27,
    question: "Which of the following is not a condition for Repeat Purchase Rule?",
    options: [
      "Within 3 months of last PO issued to the same supplier.",
      "Quantity cannot be higher.",
      "Sole Source.",
      "Price is the same or lower."
    ],
    correctAnswer: [2],
    category: "Bid Tab & PO Award",
  },
  {
    id: 28,
    question: "Which of the following statement is true?",
    options: [
      "Both Projects and non-Projects procurement can issue PO to PASL suppliers.",
      "Projects procurement can only issue RFQs to ASL suppliers.",
      "For Projects procurement, sealed-bid process is optional for PO value greater than US$500,000.",
      "For non-Projects procurement, PO can be issued to DSL suppliers if PO value is less than US$500."
    ],
    correctAnswer: [1],
    category: "RFQ/RFP",
  },
  {
    id: 29,
    question: "If quotations are submitted to end-users directly on a frequent basis, what is the recommended course of action?",
    options: [
      "Procurement Head to recommend to issue a stern warning to the end user via end user's manager.",
      "Request Procurement Head to provide approval for end-users to receive quotations from suppliers.",
      "Request those end-users to provide email juustification for receiving the quotations from suppliers.",
      "Reject all PRs submitted by those end-users."
    ],
    correctAnswer: [0],
    category: "RFQ/RFP",
  },
  {
    id: 30,
    question: "Procurement Departments are recommended to review all open PO regularly. What is the recommended period?",
    options: ["Monthly", "3 monthly.", "6 monthly.", "12 monthly."],
    correctAnswer: [0],
    category: "PO Management",
  },
  {
    id: 31,
    question: "Minor Purchase is NOT applicable for which group of items?\n(a) Production\n(b) IT\n(c) CAPEX\n(d) Office stationery",
    options: ["(a) and (b).", "(b) and (c).", "(b) and (d).", "(a) and (c)."],
    correctAnswer: [3],
    category: "PR Creation",
  },
  {
    id: 32,
    question: "End-user who wants to know the PO price can obtain the information from the following approver. Which is the correct sequence?\n(a) Material Controller / Procurement Head\n(b) End-user manager(s), or higher level (if applicable), who are approver(s) in the Bid Tab/CES/QES.",
    options: ["(a) then (b).", "(b) then (a)."],
    correctAnswer: [1],
    category: "General",
  },
  {
    id: 33,
    question: "For purchases that require trade licenses, can RFQ be issued to the supplier in the event that the trade license is expired pending renewal?",
    options: ["Yes", "No"],
    correctAnswer: [1],
    category: "RFQ/RFP",
  },
  {
    id: 34,
    question: "For new vendor, passing score for pre-qualification is 50. What is the performance evaluation score to be attained for a supplier to be retained as ASL?",
    options: ["50", "60", "70", "80"],
    correctAnswer: [1],
    category: "Supplier Management",
  },
  {
    id: 35,
    question: "John, the Manager for Maintenance Dept, recommended a new vendor for the supply of spare parts. Which is the most appropriate approach to take?",
    options: [
      "John is to be removed from all decision-making in the supplier selection processes.",
      "John can be an approver in the Technical Evaluation team as long as there are other approvers in the Technical Evaluation team.",
      "John is to be removed as a PR approver only but can be in the Technical Evaluation team.",
      "None of the options"
    ],
    correctAnswer: [0],
    category: "Supplier Registration & Selection",
  },
  {
    id: 36,
    question: "Is a Purchase Order a legally binding contract?",
    options: ["Yes", "No"],
    correctAnswer: [0],
    category: "PO Management",
  },
  {
    id: 37,
    question: "Buyer A's RFQ closing date has reached, however, only 2 valid bids have been received. The 3rd supplier has not responded. Which option is not allowed for the Buyer to take?",
    options: [
      "Void this RFQ process.",
      "Submit available quotations and apply for 3-bid exemption.",
      "Request Procurement Manager to extend RFQ closing date",
      "Send RFQ to a new supplier and obtain the 3rd quotation from this supplier."
    ],
    correctAnswer: [3],
    category: "RFQ/RFP",
  },
  {
    id: 38,
    question: "Supplier Z is selected as the supplier as the lowest priced supplier for 5 computer desktops. After negotiating on the phone, Buyer A manages to get a further discount of US$50 per desktop. What should buyer A do next?",
    options: [
      "Amend the final price on the bid tab and issue purchase order to supplier based on final price",
      "Request the supplier to send and confirm the final price in writing before issuing purchase order",
      "Request the supplier to send the final price via whatsapp so that it is official",
      "Amend the price manually on the quotation sent by supplier before they change their mind"
    ],
    correctAnswer: [1],
    category: "Price Negotiation",
  },
  {
    id: 39,
    question: "Before joining the procurement department, Buyer A was in the Logistics Department and was responsible for the Goods Receipt for materials in SAP. After joining the procurement department, Buyer A discovered that he is still able to perform Goods Receipt. What should Buyer A do?",
    options: [
      "Carry on with work as usual, although there is no need for Buyer A to use the Goods Receipt function.",
      "Highlight the issue to Procurement Head and cease using the Goods Receipt function immediately",
      "Help Logistics Department with Goods Receipt so that users can obtain their parts faster.",
      "None of the options"
    ],
    correctAnswer: [1],
    category: "General",
  },
  {
    id: 40,
    question: "Mill procurement can RFQ from NSL and DSL suppliers during sourcing activities.",
    options: ["True", "False"],
    correctAnswer: [1],
    category: "RFQ/RFP",
  },
  {
    id: 41,
    question: "COPE waiver is not allowed under which scenario?",
    options: [
      "Pre-qualification of OEMs",
      "Re-qualification of a NSL supplier whom had obtained COPE waiver during onboarding.",
      "All re-qualification scenarios of a DSL supplier",
      "None of the options"
    ],
    correctAnswer: [3],
    category: "Supplier Registration & Selection",
  },
  {
    id: 42,
    question: "What is the maximum validity of a Sole Supplier List?",
    options: ["3 months", "6 months", "9 months", "12 months"],
    correctAnswer: [1],
    category: "Supplier Registration & Selection",
  },
  {
    id: 43,
    question: "What are the pre-requisites for buyers to have access to SAP ECC?",
    options: [
      "Complete E-COPE and attempted E-Learning tests",
      "Passed E-Learning tests",
      "Complete E-COPE and passed E-Learning tests",
      "Complete E-COPE"
    ],
    correctAnswer: [2],
    category: "General",
  },
  {
    id: 44,
    question: "First time purchases will not have cost savings recorded.",
    options: ["True", "False"],
    correctAnswer: [0],
    category: "Bid Tab & PO Award",
  },
  {
    id: 45,
    question: "Buyer must follow which process when an end-user dictates to Buyer to buy a specific brand of pump?",
    options: [
      "User Specified Source",
      "Normal sourcing process",
      "3-Bid exemption",
      "Sole Source"
    ],
    correctAnswer: [1],
    category: "RFQ/RFP",
  },
  {
    id: 46,
    question: "When to use MMF02 and MMF40 ?",
    options: [
      "MMF40 is filled by supplier for yearly audit. MMF02 is used for internal evaluation with based on MMF40 to justify supplier maintain qualification to be an ASL supplier",
      "MMF40 is filled by supplier for change of supplier details. MMF02 is used for internal finance approval with based on MMF40.",
      "MMF40 is filled by suppliers for application to be an ASL supplier. MMF02 is used for internal evaluation with based on MMF40 to pre-qualify supplier as an ASL supplier.",
      "None of the options"
    ],
    correctAnswer: [2],
    category: "Supplier Registration & Selection",
  },
  {
    id: 47,
    question: "Which definition best describe NSL suppliers and DSL suppliers?",
    options: [
      "NSL suppliers are categories to support in OPEX purchase only. DSL suppliers are categories to support in CAPEX purchases only.",
      "NSL are suppliers that are banned by BU locally. DSL are suppliers that are banned by RGE globally.",
      "NSL is known as New-Supplier-List. DSL is known as Deleted-Supplier-List.",
      "None of the options"
    ],
    correctAnswer: [1],
    category: "Supplier Management",
  },
  {
    id: 48,
    question: "When is Non-Disclosure Agreement (NDA) applied?",
    options: [
      "Suppliers to sign NDA before buyer sending the RFP and/or sharing confidential information",
      "Suppliers to sign NDA after buyer sending the RFP and/or sharing confidential information",
      "Buyer to sign NDA before receiving gifts from suppliers",
      "Buyer to sign NDA after receiving gifts from suppliers"
    ],
    correctAnswer: [0],
    category: "RFQ/RFP",
  },
  {
    id: 49,
    question: "Upon receiving an approved USS form (MMF13), what is the first step for Buyers?",
    options: [
      "Request approval from the end-user",
      "Obtain a quotation from USS and award the contract to USS immediately",
      "Obtain a quotation from USS and conduct market comparison",
      "Review the end-user's supplier choice"
    ],
    correctAnswer: [2],
    category: "PR Creation",
  },
  {
    id: 50,
    question: "If a supplier other than User Specified Source (USS) is commercially better, what should the Buyer do next?",
    options: [
      "Award the contract to the better supplier immediately",
      "Request the end-user to reconsider whether to continue the USS process or to allow procurement to conduct competitive bidding",
      "Apply for a 3 bids exemption if fewer than 3 valid quotations are received",
      "Let the Procurement Manager decide which vendor to award the contract to"
    ],
    correctAnswer: [1],
    category: "PR Creation",
  },
  {
    id: 51,
    question: "If the Buyer is unable to obtain 3 valid quotations, what action should be taken?",
    options: [
      "Choose the lowest quote available, even if fewer than 3 quotations are received",
      "Apply for a 3 bids exemption approval",
      "Conduct a 2nd round of sourcing events to gather additional quotations",
      "Request user to raise USS Form (MMF13)"
    ],
    correctAnswer: [1, 2],
    category: "Bid Tab & PO Award",
  },
  {
    id: 52,
    question: "Which of the following is true regarding minor purchases?",
    options: [
      "Minor purchases may exceed USD 500.",
      "Minor purchases are only allowed for CAPEX and Production purchases.",
      "Minor purchases must be less than USD 500 or its local currency equivalent.",
      "The Procurement Head can dictate a higher value for minor purchases than USD 500."
    ],
    correctAnswer: [2],
    category: "PR Creation",
  },
  {
    id: 53,
    question: "What is the maximum total value allowed for minor purchases without requiring a purchase order (PO)?",
    options: ["<USD 1000", "<USD 500", "<USD 100", "No limit"],
    correctAnswer: [1],
    category: "PR Creation",
  },
  {
    id: 54,
    question: "Which of the following types of purchases does NOT require a purchase order (PO)?",
    options: [
      "All production-related purchases",
      "Minor purchases exceeding USD 500",
      "Minor purchases & the list of purchases approved by the Finance department (e.g., levy, tax, travel, stationery)",
      "All purchases made by the Procurement Head"
    ],
    correctAnswer: [2],
    category: "Bid Tab & PO Award",
  },
  {
    id: 55,
    question: "What should happen when new items are added to the list of purchases that do not require a purchase order?",
    options: [
      "The list should be updated and approved by the Procurement Head.",
      "The list should be updated and approved by the Finance department.",
      "The total value for each item should be limited to USD 500.",
      "The list should not be updated until the next fiscal year."
    ],
    correctAnswer: [1],
    category: "Bid Tab & PO Award",
  },
  {
    id: 56,
    question: "Reference to SOP 502.3.3.2 - PO Creation And Approval Process. A request has been made to purchase an item which is in the finance approved list, with a total value of US$700. 2 quotations received. What should the buyer do?",
    options: [
      "3-bid exemption form is NOT needed and PO is NOT required",
      "Submit a 3-bid exemption form for approval and PO is NOT required",
      "Insufficient information",
      "None of the options"
    ],
    correctAnswer: [1],
    category: "Bid Tab & PO Award",
  },
  {
    id: 57,
    question: "A request has been made to purchase an item with a total value of USD 200. Is a PO required?",
    options: [
      "Yes, because all purchase needs a PO",
      "No, as it is lower than 500 USD",
      "Insufficient information",
      "None of the options"
    ],
    correctAnswer: [2],
    category: "Bid Tab & PO Award",
  },
  {
    id: 58,
    question: "User informed Buyer that he was in discussion with a prospective supplier over the development of a new part. Technical information and data may need to be shared. What advice can the Buyer suggest to the user?",
    options: [
      "User should assess if NDA should be signed with supplier before releasing information and data to supplier.",
      "Users are not allowed to contact and hold any discussions with any suppliers. Only Procurement is allowed to contact suppliers.",
      "User are only allowed to contact and hold discussions with ASL suppliers directly only.",
      "User should limit discussion to non-commercial and non-price related topics only. NDA is not relevant since there is no RFQ or PO issued."
    ],
    correctAnswer: [0],
    category: "RFQ/RFP",
  },
  {
    id: 59,
    question: "Which of the following statement is correct about NDAs?",
    options: [
      "NDA is required prior to inviting any suppliers to participate in RFQ/RFPs.",
      "NDA template should be requested from BU/BG's local legal department.",
      "There is only one type of NDA template for each BU/BG.",
      "Procurement has nothing to do with NDA. User or Legal will send to the supplier if needed."
    ],
    correctAnswer: [1],
    category: "RFQ/RFP",
  },
  {
    id: 60,
    question: "Buyer received TES from Technical Evaluator and noted that scoring is not consistent for the same remarks. What should the buyer do?",
    options: [
      "Since TES is approved, buyer can just accept it as it is.",
      "Clarify with Technical Evaluator on the scoring methodology. Buyer has a responsibility to ensure evaluation is fair.",
      "Highlight the concern in CES as Buyer is only responsible for the CES.",
      "Edit the TES to make it more fair since it is obviously a mistake from Technical Evaluator."
    ],
    correctAnswer: [1],
    category: "Bid Tab & PO Award",
  },
  {
    id: 61,
    question: "Supplier A was given a \"Pass\" rating in a TES. Buyer however received a call from assigned Technical Evaluator later that Supplier A was discovered to have a bad performance record and should not be awarded the order. How should the buyer proceed?",
    options: [
      "Remove Supplier A from CES since technical evaluator says supplier is not performing.",
      "Request technical evaluator to revise TES to indicate Supplier A did not pass TES.",
      "Include Supplier A in CES, but indicate in the comments that Supplier A should not be considered due to bad performance.",
      "Amend the TES on technical evaluator's behalf and countersign against the change."
    ],
    correctAnswer: [1],
    category: "Bid Tab & PO Award",
  },
  {
    id: 62,
    question: "A contract is due to expire soon. Buyer would like to perform a contract renewal. Which of the following is correct?",
    options: [
      "If contract has an auto renewal clause, no further action is needed since all rates, terms and conditions are the same.",
      "Buyer should check if stakeholders still require the services and/or if there are any changes to usage.",
      "Buyer should perform a market survey to check if existing rates are competitive.",
      "Buyer needs to seek management approval for contract renewal."
    ],
    correctAnswer: [1, 2, 3],
    category: "Bid Tab & PO Award",
  },
  {
    id: 63,
    question: "What should mill operations (non-project) buyer check for before submitting bidder's list for approval in sealed bid process?",
    options: [
      "All suppliers needs to be in ASL status to participate in RFQ/RFP.",
      "No suppliers should be having DSL and DSL-OS status",
      "All suppliers needs to be in ASL status before PO can be issued.",
      "All of the options"
    ],
    correctAnswer: [1],
    category: "RFQ/RFP",
  },
  {
    id: 64,
    question: "Buyer conducted a non-sealed bid RFQ and received only 2 bids after RFQ had closed. Which of the following are acceptable follow up action(s) for the buyer?",
    options: [
      "Inform all suppliers that RFQ closing date will be extended",
      "Inform suppliers who participated that RFQ will be called again.",
      "Raise a 3 Bid Exemption Request and proceed with bid evaluation process",
      "Raise a request to add material and supplier into Sole Source list."
    ],
    correctAnswer: [1, 2],
    category: "RFQ/RFP",
  },
  {
    id: 65,
    question: "After successful prequalification, Buyer wants to promote a supplier from PASL to ASL. He noted in GCS that there are other BU/BGs subscribed to the supplier. How shall he proceed?",
    options: [
      "He can submit a request in GCS to change the supplier status directly without informing subscribed BU/BGs.",
      "He should inform the other BU/BGs to prequalify the supplier and only submit the status change request in GCS after the supplier is prequalified by all affected BU/BG.",
      "As this change affects all subscribed BU/BGs, he will need to seek their concurrence before submitting status change request in GCS.",
      "None of the options"
    ],
    correctAnswer: [1],
    category: "Global Coding System",
  },
  {
    id: 66,
    question: "RGE practices a \"ZERO Tolerance Policy\" on fraud.",
    options: ["True", "False", "Maybe", "Not sure"],
    correctAnswer: [0],
    category: "General",
  },
  {
    id: 67,
    question: "I must submit declaration according to existing process requirement when I am aware of any ex-RGE employee is working in a supplier's company.",
    options: ["False", "Maybe", "True", "Not sure"],
    correctAnswer: [2],
    category: "General",
  },
];